package com.thesis.cloudsim.dto;

import lombok.Builder;
import lombok.Data;
import java.util.Map;
import java.util.List;

/**
 * Metadata structure for MATLAB-generated plots
 * 
 * I created this DTO to carry semantic information about each plot,
 * enabling context-aware interpretations based on the actual MATLAB plots
 */
@Data
@Builder
public class PlotMetadata {
    private String plotId;
    private PlotType type;
    private String title;
    private String description;
    private String filename;
    private List<String> dataSeriesNames;
    private Map<String, Object> dataPoints;
    private PlotInterpretation interpretation;
    
    /**
     * Enumeration of plot types generated by generateComparisonPlots.m
     * Each type maps to a specific plot in the MATLAB script
     */
    public enum PlotType {
        PERFORMANCE_METRICS("performance_metrics", "Main performance metrics bar chart", "metrics.png"),
        DETAILED_ANALYSIS("detailed_analysis", "Detailed performance analysis with 4 subplots", "detailed.png"),
        VM_UTILIZATION("vm_utilization", "VM resource utilization bar chart", "vm_utilization.png"),
        ENERGY_ANALYSIS("energy_analysis", "Energy consumption and efficiency analysis", "energy.png"),
        RADAR_CHART("radar_chart", "Multi-dimensional performance radar chart", "radar.png"),
        TIME_METRICS("time_metrics", "Time-based metrics subplot", "detailed.png#time"),
        EFFICIENCY_METRICS("efficiency_metrics", "Efficiency metrics subplot", "detailed.png#efficiency"),
        LOAD_DISTRIBUTION("load_distribution", "Load distribution pie chart", "detailed.png#pie");
        
        private final String code;
        private final String description;
        private final String filePattern;
        
        PlotType(String code, String description, String filePattern) {
            this.code = code;
            this.description = description;
            this.filePattern = filePattern;
        }
        
        public String getCode() {
            return code;
        }
        
        public String getDescription() {
            return description;
        }
        
        public String getFilePattern() {
            return filePattern;
        }
        
        /**
         * I provide a method to detect plot type from filename
         */
        public static PlotType fromFilename(String filename) {
            if (filename.contains("metrics.png")) return PERFORMANCE_METRICS;
            if (filename.contains("detailed.png")) return DETAILED_ANALYSIS;
            if (filename.contains("vm_utilization.png")) return VM_UTILIZATION;
            if (filename.contains("energy.png")) return ENERGY_ANALYSIS;
            if (filename.contains("radar.png")) return RADAR_CHART;
            return PERFORMANCE_METRICS; // Default
        }
    }
    
    /**
     * Structured interpretation for each plot
     * This provides rich contextual information for the frontend
     */
    @Data
    @Builder
    public static class PlotInterpretation {
        private String summary;
        private String keyFindings;
        private String recommendations;
        private Map<String, String> metricExplanations;
        private String visualPattern;
        private String comparisonInsight;
        private PerformanceGrade performanceGrade;
    }
    
    /**
     * Performance grading for visual interpretation
     */
    public enum PerformanceGrade {
        EXCELLENT("Excellent", "A+", "#10b981"),  // Green
        VERY_GOOD("Very Good", "A", "#22c55e"),
        GOOD("Good", "B+", "#84cc16"),
        SATISFACTORY("Satisfactory", "B", "#eab308"),  // Yellow
        NEEDS_IMPROVEMENT("Needs Improvement", "C", "#f97316"),  // Orange
        POOR("Poor", "D", "#ef4444");  // Red
        
        private final String label;
        private final String grade;
        private final String color;
        
        PerformanceGrade(String label, String grade, String color) {
            this.label = label;
            this.grade = grade;
            this.color = color;
        }
        
        public String getLabel() { return label; }
        public String getGrade() { return grade; }
        public String getColor() { return color; }
    }
}
